/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/env.d.ts` (hash: bdb5666e93577de5f65c4d47890622cb)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	ATLAS_ORIGIN: string;
	ATLAS_DEPLOYMENT: string;
	ATLAS_LOCAL_HTTP: string;
	ATLAS_ALLOWED_ORG: string;
	ATLAS_ALLOWED_USER_IDS: string;
	ATLAS_DEFAULT_REPOSITORY: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	ATLAS_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ATLAS_ORIGIN" | "ATLAS_DEPLOYMENT" | "ATLAS_LOCAL_HTTP" | "ATLAS_ALLOWED_ORG" | "ATLAS_ALLOWED_USER_IDS" | "ATLAS_DEFAULT_REPOSITORY" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "ATLAS_ENCRYPTION_KEY">> {}
}
